# DRY database.yml
common: &common
  adapter: mysql
  username: amble
  password: amble
  host: localhost
  encoding: utf8
  pool: 20

development:
  <<: *common
  database: amble_dev

test:
  <<: *common
  database: amble_test

production:
  <<: *common
  database: amble
  username: amble
  password: "Clios487.Ronal"