common: &common
  bucket: amble-production-attached-files
  access_key_id: AKIAIHG7PL2CVFGFZZIQ
  secret_access_key: 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

development:
  <<: *common
  secret_access_key: DISABLED_FOR_WRITE

test:
  <<: *common
  secret_access_key: DISABLED_FOR_WRITE

production:
  <<: *common